Repository TitaniumTigers4829/mako-robot-code-2025, pull requests merged in 2025-01, with the labels that each got.

#17 Fixed actions
  .github/workflows/build.yml
Labels: bug

#20 Moved thread manager into extras and made it more generalized
  src/main/java/frc/robot/extras/util/ThreadManager.java
  src/main/java/frc/robot/subsystems/vision/PhysicalVision.java
Labels: regular priority

#11 Added comments and remove useless code
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/drive/DriveCommand.java
  src/main/java/frc/robot/commands/drive/DriveCommandBase.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/SwerveDrive.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModule.java
  src/main/java/frc/robot/subsystems/swerve/gyro/GyroInterface.java
  src/main/java/frc/robot/subsystems/swerve/gyro/PhysicalGyro.java
  src/main/java/frc/robot/subsystems/swerve/gyro/SimulatedGyro.java
  src/main/java/frc/robot/subsystems/swerve/module/ModuleInterface.java
  src/main/java/frc/robot/subsystems/swerve/module/PhysicalModule.java
  src/main/java/frc/robot/subsystems/swerve/odometryThread/OdometryThread.java
  src/main/java/frc/robot/subsystems/swerve/odometryThread/OdometryThreadReal.java
Labels: documentation

#3 Update to official whippylib 2025
  build.gradle
  vendordeps/photonlib-v2025.1.1-rc1.json
Labels: regular priority

#24 Robottype
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/drive/DriveCommand.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModule.java
  src/main/java/frc/robot/subsystems/swerve/module/CompModule.java
  src/main/java/frc/robot/subsystems/swerve/module/DevModule.java
  src/main/java/frc/robot/subsystems/swerve/odometryThread/OdometryThread.java
  src/main/java/frc/robot/subsystems/vision/SimulatedVision.java
Labels: enhancement

#12 Abigail swrve x stance
  src/main/java/frc/robot/commands/drive/XState.java
  src/main/java/frc/robot/subsystems/swerve/SwerveDrive.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModule.java
  src/main/java/frc/robot/subsystems/swerve/module/CompModule.java
  src/main/java/frc/robot/subsystems/swerve/module/DevModule.java
  src/main/java/frc/robot/subsystems/swerve/module/ModuleInterface.java
  src/main/java/frc/robot/subsystems/swerve/module/SimulatedModule.java
Labels: enhancement

#37 Vision threading fix
  src/main/java/frc/robot/subsystems/vision/PhysicalVision.java
  src/main/java/frc/robot/subsystems/vision/VisionInterface.java
  src/main/java/frc/robot/subsystems/vision/VisionSubsystem.java
Labels: enhancement

#46 remove odometry thread, device can bus, and minor clean up
  src/main/java/frc/robot/extras/util/DeviceCANBus.java
  src/main/java/frc/robot/subsystems/swerve/SwerveDrive.java
  src/main/java/frc/robot/subsystems/swerve/gyro/GyroInterface.java
  src/main/java/frc/robot/subsystems/swerve/gyro/PhysicalGyro.java
  src/main/java/frc/robot/subsystems/swerve/gyro/SimulatedGyro.java
  src/main/java/frc/robot/subsystems/swerve/module/CompModule.java
  src/main/java/frc/robot/subsystems/swerve/module/DevModule.java
  src/main/java/frc/robot/subsystems/swerve/odometryThread/OdometryThread.java
  src/main/java/frc/robot/subsystems/swerve/odometryThread/OdometryThreadReal.java
  src/main/java/frc/robot/subsystems/vision/PhysicalVision.java
Labels: bug, do not merge (yet)
